[project]
name = "birthday problem simulation"
version = "0.1.0"
description = "a python simulation for the birthday problem"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
]
